name: terraform-fmt
description: Rewrite terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions:v1.8.0
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
